try to fix alpine's missing RUNTIME_DIR
=== ERROR while compiling tsdl-image.0.5 =====================================#
context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.0 | pinned(https://github.com/sanette/tsdl-image/archive/0.5.tar.gz)
path                 ~/.opam/4.14/.opam-switch/build/tsdl-image.0.5
command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p tsdl-image -j 255 @install @runtest
exit-code            1
env-file             ~/.opam/log/tsdl-image-7-7b60c0.env
output-file          ~/.opam/log/tsdl-image-7-7b60c0.out
output ###
File "test/dune", line 2, characters 7-11:
2 |  (name test)
           ^^^^
(cd _build/default/test && ./test.exe)
INFO: Loading Sdl_image, Target = linux
error: XDG_RUNTIME_DIR not set in the environment.
commandline read: test.exe
(*) Direct/Thread: Started 'SigHandler' (66) [CRITICAL - OTHER/0] <133880>...

   ~~~~~~~~~~~~~~~~~~~~~~~~~| DirectFB 1.7.7 |~~~~~~~~~~~~~~~~~~~~~~~~~~
        (c) 2012-2015  DirectFB integrated media GmbH
        (c) 2001-2015  The world wide DirectFB Open Source Community
        (c) 2000-2004  Convergence (integrated media) GmbH
      ----------------------------------------------------------------

(*) DirectFB/Core: Single Application Core. (2022-04-15 08:17)
(*) Direct/Memcpy: Using libc memcpy()
(*) Direct/Thread: Started 'Fusion Dispatch' (67) [MESSAGING - OTHER/0] <133880>...
(!) System/DevMem: Please supply 'video-phys = 0xXXXXXXXX' and 'video-length = XXXX' options!
(!) DirectFB/Core: Could not initialize 'system_core' core!
    --> An invalid argument has been specified